backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "general_config/config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Tagebuch Navigation"
            name: "tagebuch_navigation"
            widget: "string"
          - label: "Journalismus Navigation"
            name: Journalismus_navigation"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "Instagram account"
            name: "instagram_account"
            widget: "string"

      - name: "home"
        label: "Home Page"
        file: "general_config/home.json"
        description: "Home Page Settings"
        fields:
          - name: "image_xl"
            label: "image_xl"
            widget: "image"
            media_library:
              config:
                multiple: false
          - name: "image_lg"
            label: "image_lg"
            widget: "image"
            media_library:
              config:
                multiple: false
          - name: "image_md"
            label: "image_md"
            widget: "image"
            media_library:
              config:
                multiple: false
          - name: "image_loading"
            label: "image_loading"
            widget: "image"
            media_library:
              config:
                multiple: false
          - label: "image_credits"
            name: "image_credits"
            widget: "string"
          - label: "image_credits_url"
            name: "image_credits_url"
            widget: "string"
          - label: "Into Headline"
            name: "intro_headline"
            widget: "string"
          - label: "Intro Text"
            name: "intro_text"
            widget: "markdown"
          - label: "Book Feature"
            name: "book_featured"
            widget: "relation"
            collection: "books"
            search_fields: ["title"]
            value_field: "title"

  - name: "books"
    label: "Bücher"
    folder: "src/pages/buecher"
    extension: "mdx"
    format: "frontmatter"
    create: true
    summary: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Body"
        name: "body"
        widget: "markdown"
      - name: "image"
        label: "image"
        widget: "image"
        media_library:
          config:
            multiple: false
        
  - name: "jornalismus"
    label: "Journalismus"
    folder: "src/pages/journalismus"
    extension: "mdx"
    format: "frontmatter"
    create: true
    summary: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Text Type"
        name: "type"
        widget: "string"
      - label: "Publisher"
        name: "publisher"
        widget: "string"
      - label: "Text URL"
        name: "url"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - name: "image"
        label: "image"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "tagebuch"
    label: "Tagebuch"
    folder: "src/pages/tagebuch"
    extension: "mdx"
    format: "frontmatter"
    create: true
    summary: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Body"
        name: "body"
        widget: "markdown"
   
  - name: "impressum"
    label: "impressum"
    file: "impressum.json"
        fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
